### ISSUE TITLE
"conferences and trainings" vs. "Prof Dev / Training"

### ISSUE THREAD

**Issue by batemapf** [18F/tock#101]
need to clean up redundant titles

**Comment by batemapf** [comment]
changed "conferences and trainings" to "conferences"

**Comment by wslack** [comment]
I think that to be considered part of employed time, conferences are either outreach opportunities or prof dev opportunities - I don't think they should have their own line if we are treating all EDU stuff with a single line. I would advocate getting rid of this one.

**Comment by batemapf** [comment]
@wslack please advise if further changes to the conferences / trainings / prof dev lines

**Comment by wslack** [comment]
After talking to @StephanieRivera, we should eliminate the "conferences" line. It exists because:
https://github.com/18F/tock/issues/77 and https://github.com/18F/tock/issues/82 appeared around the same time, but going to a conference isn't 18F time unless you are doing hiring, outreach, or Prof Dev work, so it doesn't need to be tracked separately.

**Comment by batemapf** [comment]
resolved
