### ISSUE TITLE
Investigate jquery removal

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#1044]
We don't use jquery a lot, but we do use it, which leads to the eventual Snyk unhappiness as our version falls out of date. Let's look at dropping the dependency in favor of vanilla JS, but let's timebox our effort to a day or so. If it takes longer than that it's probably not worth it.

**Comment by cryptofilegsa** [comment]
Consider jadudm proposal here: https://github.com/jadudm/replacing-jquery

**Comment by mark-meyer** [comment]
That's an interesting proposal. I looks like jQuery is used pretty intensively throughout the front-end code, so the danger of creating a jQuery clone is real. As a small example, the constructor will need to be quite a bit more robust to handle the various kinds of arguments as seen in `populateHourTotals()` :

```
    $('.entries .entry').each(function (i, entry) {
      entry = $(entry);
      var project = $('.entry-project select', entry).val();
      var hours = $('.entry-amount input', entry).val();
      ...
```

I wonder how the work to create and maintain this would compare to introducing a front-end framework like Vue.js?

**Comment by tbaxter-18f** [comment]
I remain unconvinced that we need any JS framework for lib for our modest JS needs. I think for the purposes of this issue I'd just like a good investigation of what it would take... maybe I'm wrong. The outcome of this could just be a raft of new issues to address it bit by bit, culminating in an eventual story that actually removes it.

**Comment by jadudm** [comment]
I agree completely that the clone creation is real. And yes, I saw that example in the code... I assume that, if we went down this road, that we'd have a MiniQuery (pick a name... *NotActuallyJQuery*?) that did what we needed, and no more (e.g. it would cover the use cases that currently exist). I personally see a number of follow-ons that are necessary to trust it: possible tests for just the class, integration tests, etc.

My thinking was essentially "one way to remove JQuery from the dependencies would be to introduce a new, lighter abstraction but leave the front-end code intact." In other words, leave the syntax and semantics intact, which I assume would reduce the likelihood of introducing new errors into the codebase. But, I worry that it might encourage (tacitly/explicitly) the continued use of *NotActuallyJQuery*. That, long term, would probably be Bad<sup>TM</sup>.

So... it's a thought, but I don't have history with the project, and don't know whether the tradeoff of a (probably?) light lift now to eliminate a ding from Snyk is desirable vs., say, a framework shift.

Or, just rewriting all the $() statements in vanilla JS. But, there are a bunch of them.

**Comment by tbaxter-18f** [comment]
I could easily be convinced otherwise, but I think our best outcome for this issue is to catalog what it will take to move to vanilla JS, but not actually try to bite it all off now.

**Comment by jadudm** [comment]
*Previous claims of "there are a bunch of them" re: JQuery statements were greatly exaggerated, and unsubstantiated by evidence. Those responsible for the sacking have been sacked.*

It looks like there's around 55 uses of "$(" in the code. Almost all of the usage is in [timecard.js](https://github.com/18F/tock/blob/347ebe3476643efa5a98b852cad773391031a946/tock/tock/static/js/components/timecard.js), a few uses in templates (it seems), and one or two in some tests. (Although, I'm not certain what "$$(" is without digging. It feels like an escape, so I'll count it as something to check just the same.)

After poking at an abstraction a bit more yesterday, writing some kind of wonky wrapper library feels like 1) a lot of (error-prone) work, 2) would lead to a weird little library floating around, and 3) given only 55 uses of "$(" in the codebase (which I admit I am assuming is the only way to invoke JQuery), I personally think it would be easier just to rewrite the JQueries, as they're generally clean/straight-forward in form/structure. I'm willing to take on this change, once I have everything set up.

My counts are based on a little Python script. It walks every file in the `tock` tree, goes line by line, and looks for usages of "\\$\\(" as a regex. It bails on anything that the utf-8 reader can't eat, but that should (*cough*) only be things like fonts, images, and so on. 

https://gist.github.com/jadudm/c576a55ed6ee6977a1ff89373babbf31

**Comment by jadudm** [comment]
So: reporting work/findings here. Input wanted, either on-ticket or some live discussion.

I took the approach of extending the Jest/Puppeteer tests to cover more of timecard.js, so that as I removed jQuery, I could have confidence that behavior was being preserved. It is my belief that those tests were executed from outside the containerized environments. Put another way, Puppeteer requires a headless Chromium instance, which requires quite a few X11 libs which our containers do not have. Therefore, it seems highly unlikely that the few tests that existed (for checking rounding) were integrated in the automated testing framework.

I can proceed a number of ways, but they feel like:

1. **Remove jQuery while "checking that it works."** This would mean I try, through human-clicking-on-webpage-means, to make sure that my changes do not break the timecard form.

2. **Run tests outside of containers**. To do this, I would do my containerized work in one part of the local filesystem, and run the tests from another. This way, the node environment for the tests is separate from the node environment of the containers.

3. **Build a test container for the front-end**. This would mean spinning up a new dev container that contains the X11 libs, and it could then be asked to drive front-end tests against Tock. This may be of use as a model/instance for other 18F projects: we would then have a container ready-to-go for running a headless Chromium against projects.

I think that sums it up. I have already added a number of tests and was, without realizing it, enacting #2. This then broke Tock, because of the shared node_modules directory. (Broke *my local Tock*, not Tock in general.)

Thoughts?

**Comment by tbaxter-18f** [comment]
Well, you're doing the work, which one feels best to you?

My vote would probably be #2, with the caveat that we write an issue to move toward a more integrated solution, but I could also be _very_ easily swayed toward another direction.

**Comment by jadudm** [comment]
#2 has the best velocity. Tests are already in place that run with `npm test` on the command line. Integration with testing frameworks is its own work, and leaving testing aside feels fragile. So, barring any strong views, I'll continue without wandering down a Docker rabbit hole.

**Comment by arouault** [comment]
@jadudm some relevant notes from today's standup 

**path forward from Heather:** 

- biggest chunk of jquery is time card page - dropdown and dashboard chart 
- start with dropdown [this is the place where the library of concern] 
- we can refactor the frontend in pieces 
- compartmentalize different problems to solve (removing jquery for security, testing approach, react or not) 

She'll also follow up directly!

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
