### ISSUE TITLE
Hours tocked to `microrequest` projects should count towards IC billable hours

### ISSUE THREAD

**Issue by Jkrzy** [18F/tock#1084]
A handful of project lines tracking `microrequest` are not being included as billable hours in utilization reports.  e.g., `1149`

This is because
> We don't bill the partner for them, which is why the tock line isn't listed as billable, but they should count towards the IC's billable hours

We'll need to work with the account management team on this one to ensure they can continue to pull the data they need.

This may take the form of being able to differentiate `Accounting Codes` which are or are not invoiced in addition to their `billable` status.
 
## We'll know we're done when:
- [ ] Microrequest tock lines are considered billable and included in utilization reporting
- [ ] <s>AM</s> Finance team is able to pull data required for invoicing without including unecessary data from these same `microrequest` projects.

**Comment by tbaxter-18f** [comment]
We'll need a way to differentiate "billable" microrequests (with a partner) vs "non-billable" (usually internal).

@hannahkane & @rrefoy do y'all have thoughts?

**Comment by hannahkane** [comment]
@tbaxter-18f - the partner-billable microrequests would show up on the project tock line. Non-billable microrequests would show up as the general non-billable. The four TTS-specific microrequests are the only exception (that I know of). It's Matt Spencer's (gh handle?) opinion that matters, but I'm wondering what havoc it would wreak if we marked them as billable in tock?

**Comment by rrefoy** [comment]
Can i see a use case for what @Jkrzy is describing? Why wouldn't we bill the partner for those hours?

**Comment by tbaxter-18f** [comment]
Thanks Hannah. I wasn't even thinking abou those. So we have three types of microrequests

1. small help on a project. These are already billable to the project and it's up to the IC to do so.
2. truly non-billable. These are internal writing lab requests and such. There's really no one to bill them too.
3. TTS microrequests that fall under the agreement. These are the ones @Jkrzy and @hannahkane were referring to. They're not marked as billable because they've already been billed, but I they should count toward utilization because they are money-making work, right?

Tapping in @martyspencer for visibility

**Comment by hannahkane** [comment]
@tbaxter-18f - that's right. The first two are straightforward. The third is an edge case. They're billable from the perspective of hours utilization, but the partner doesn't receive a bill as it was worked out in an overhead costs sharing conversation at the beginning of the fiscal year (I believe).

**Comment by tbaxter-18f** [comment]
Right. And currently they are not being counted toward the individual's utilization total. Since they are doing work and creating impact for the partner, we think that should count as utilization.
 
It's very helpful talking this through, though. I think this is ultimately a @martyspence call, but I think we need to do one of two things:

1. Mark the 1149-1152 microrequest lines as "billable" in Tock. This is certainly easy, but may create all sorts of downstream weirdness for Matt.
2. Create a new flag in Tock to capture pre-billed work, so we then know to count it toward utilization.

Option 2 might also make it easier to see at a glance how much of that work has been done?

**Comment by Jkrzy** [comment]
Option 2 sounds fine to me, similar to how we've excluded specific projects from utilization calculations (Out of Office). Effectively giving us project level overrides to both include or exclude from utilization reporting.

For each `Project/Tock line` 
- [ ] Add an `include_in_utilization` boolean field, defaults to that project's billable status

For the 4 edge cases we run into every week:
- [ ] Set `include_in_utilization` to `True`

Update utilization reporting to filter on the new `Project.include_in_utilization` field

This change wouldn't be visible to or otherwise impact the Finance team.

**Comment by tbaxter-18f** [comment]
I have a mild preference to `pre-billed` over `include_in_utilization`, mostly because it hews closer to the `billable`/`non-billable` pattern. But it is only a mild preference that I acknowledge makes no actual difference.

**Comment by martyspence** [comment]
I would prefer @tbaxter-18f's option #2. Aside from utilization, making these billable would muddy up our revenue reporting since all other 18F projects are reimbursed as revenue, while these are actually "paid" through a cost allocation reimbursement. If there's a way to have them count toward utilization without the billable tag that'd be my vote.

**Comment by cryptofilegsa** [comment]
Have implemented a include_in_utilization boolean in projects and made this a filterable field (yes/no/all) in the projects administrative interface.  These changes are on branch: https://github.com/18F/tock/tree/microrequest-1084

**Comment by cryptofilegsa** [comment]
initial work is in pull request #1121  which passes tests now, ready for review and merge.

We can expand definition of done for a new pull request to include:
- [ ] starting value for include_in_utilization is not just false but billable status by default
- [ ] where include_in_utilization is True a project should be included in the utilization reports regardless of it's billable status
- [ ]  [documentation for the utilization reports](https://github.com/18F/tock/blob/master/docs/utilization.md) is updated to clarify how the include_in_utilization is implemented

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
