### ISSUE TITLE
Show/Hide Timesheets Depending on Start and End Date of an Employee

### ISSUE THREAD

**Issue by seanherron** [18F/tock#114]

**Comment by zacharycohn** [comment]
Would love this. I currently see a massive list of all the timesheets I've missed out on, with no way of getting rid of them. It seems like, at the very least, reversing the order of the list of "missing" time sheets would functionally solve the problem. (I rarely have to go back to timecards I've already submitted, so they can be at the bottom. Every week, I have to submit a new one, so that should be at the top)

<img width="612" alt="screen shot 2015-08-24 at 11 14 42" src="https://cloud.githubusercontent.com/assets/614963/9443819/52c05d9e-4a51-11e5-9869-87dc150cd1f7.png">

**Comment by jessieay** [comment]
Yes please!! I find this very confusing every time I log into Tock. 

Not sure if Tock is using the TEAM API, but if it were this would be related to an issue I just opened on the TEAM API about adding start date and end date for employees: https://github.com/18F/team-api.18f.gov/issues/123

cc @mbland @mtorres252

**Comment by batemapf** [comment]
if the team api can populate the start date and end date fields already built into tock, that would be ideal.  tock will only display time cards for the dates after your start date.  so this could be done by hand when an employee is onboarded...or via the team api.... cc @mbland

**Comment by zacharycohn** [comment]
Could that field just be set to public, and we add a text field where you
can edit it yourself. Then the user can do it on Day 1, rather than adding
more tasks to Team Talent for onboarding.

**Comment by batemapf** [comment]
or if the team api is already picking this data up from somewhere, it would only need to be added in one place.

**Comment by jessieay** [comment]
@zacharycohn Team API is not currently picking up this data. I like the idea of letting employees edit their own start date. 

I pinged @mtorres253 in my previous comment because he is working with Mike Bland on figuring out how we can improve the Team API for its various use cases. I think one aspect of that is figuring out a way to make it easier for employees to add/update their information. This is another example of a use case where allowing employees to easily update their own info (perhaps outside of GitHub?) would be helpful.

**Comment by mbland** [comment]
Yes, I'm totally open to figuring out a new interface for user information I/O, as it's getting to be a PITA for even me to keep the flat YAML files and other sources up-to-date. I'm imagining we may want to have one system of record for maintaining (most of) this stuff, and expose that through the Team API for other systems like Tock, Dolores, etc. to consume.

**Comment by mtorres253** [comment]
We've talked about having a way for employees to control elements of their profile that could then be leveraged with the team API for things like this. In any case, a great idea for initial employee set-up and then letting employees update after that, and should be groomed and prioritized with team.
