### ISSUE TITLE
Improve error message re: Uchenna login problem

### ISSUE THREAD

**Issue by arouault** [18F/tock#1147]
re: https://gsa-tts.slack.com/archives/C1JFYCX3P/p1597427654367000

**Comment by Jkrzy** [comment]
Let me know if you want to chat about this one @timoballard, I can provide some context and replicate the issue for you if helpful

**Comment by timoballard** [comment]
Thanks @Jkrzy - I did some sleuthing this afternoon, here's where I'm at: Can reproduce in staging by not granting the requisite permissions during first-time login. Haven't reproduced locally due to the fake UAA provider, so I'm fiddling with a sandbox deploy to cloud.gov with a real UAA provider.

In any case, at bottom, the issue seems to be that the `cg-django-uaa` client library, as it is, doesn't expose much error detail to the `login_error` template, and so there's not much the template can confidently render beyond "authentication failed... for some reason". That said, we could make the message cleaner and offer some potential resolutions e.g., take whatever steps are necessary to grant the appropriate permissions to Tock
