### ISSUE TITLE
Slack slash command (or similar)

### ISSUE THREAD

**Issue by stvnrlly** [18F/tock#1155]
It would be cool (and way more efficient) to be able to Tock my time directly from Slack. I imagine this being something like:

- `/tock add 3 1234` to put 3 hours into Tock line 1234, 
- `/tock status` to get a quick readout of my hours so far this period, and 
- `/tock submit` to finalize it at the end of the week

This could potentially be extended in some fun(?) ways:

- `/tock report 1234` gives some kind of useful report from tock line 1234,
- `/tock submitted` outputs the percentage of people who have submitted for this period already, and
- `/tock channel add 1234` associates a Slack channel with Tock line 1234, after which `/tock channel 3` puts 3 hours into Tock line 1234

Since Tock already talks to Slack, I'm assuming that this doesn't bring up ATO issues, but it does probably require a not-insignificant lift of Slack API usage. Whether the juice is worth the squeeze for the org, I don't know, but I would definitely use this (and submit my time a little bit better) if it existed.

**Comment by Jkrzy** [comment]
🤔 At the moment, the Tock API is read-only...I'm not sure if that was an intentional decision for compliance reasons or just that there was never a need. 

We'd need to implement POST end points and make the associated updates to our SSP, we're do for an ATO renewal within the next 12 months so this may be nice timing.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
