### ISSUE TITLE
new projects not populating in user-facing pages

### ISSUE THREAD

**Issue by batemapf** [18F/tock#126]
added "usa.gov - labs" via django admin page.  not showing up in list of projects in tock user-facing page.

**Comment by jpyuda** [comment]
Any chance this is related to the `.gov` that's in the name of the project?

**Comment by seanherron** [comment]
Nope, I just tried this with another new test project and the same issue happened. This will take some debugging.

**Comment by batemapf** [comment]
also just updated info associated with a project (moved HaaS - USDS to OCSIT accounting code); update not reflected in user-facing page.

**Comment by seanherron** [comment]
It appears now ¯\(°_o)/¯

**Comment by ethanheppner** [comment]
Hey, it looks like this bug is back! I added the following projects last week, and while they show up on the admin's side as available choices, normal users aren't able to see or choose them:

"C2: Core Platform" --Replaces the old CAP Communicart project.
"C2: Public Buildings Service" --Work relating to Communicart's rollout in GSA's Public Buildings Service (PBS).
"C2: National Capital Region" --Work relating to Communicart's rollout in the DC region.

**Comment by jmcarp** [comment]
Now that #175 is merged and deployed, this should be fixed, for real. @ethanheppner or @batemapf, next time you add or modify a project, can you verify that this is working?

**Comment by ethanheppner** [comment]
Seems like it's working.
![screen shot 2015-07-09 at 12 07 38 pm](https://cloud.githubusercontent.com/assets/12718798/8601671/272f850c-2633-11e5-8852-2159a1339578.png)

**Comment by jmcarp** [comment]
Awesome. I'm closing this, hopefully for good!
