### ISSUE TITLE
selective access to projects

### ISSUE THREAD

**Issue by batemapf** [18F/tock#136]
limit the persons who can log time against a specific project

**Comment by cmc333333** [comment]
That seems like a policy problem rather than a technical one. What happens when someone's brought in for an hour to discuss some design? The project admin will have to jump through hoops to allow this one-off?

**Comment by seanherron** [comment]
I'm not a huge fan of this idea. We haven't heard a strong desire from product leads to implement this, and it would introduce a ton of complexity, both in the code but also in a process to get people added in a timely manner.

**Comment by russu** [comment]
Time cost seems like it *could* be more later to try and identify why person x spent time against a project than to place controls and expectations up front.

Here's an explicit example:

USDS Web Standards has a very fixed budget that has to be closely monitored. A lot of people are passionate about the project and want to participate, however, the budget and the persons are going to need to be closely managed. While it may be possible to contribute beyond our specific resources as volunteer time, it would be helpful to ensure the time is booked, approved, etc. accordingly, in order to maintain more accurate views into the budget tracking, etc.

I realize that there's an opportunity for additional overhead in "just booking time to a project as needed assistance" - the hypothesis is that there is potentially more overhead in justifying time against a project through tracking down persons, asking for rationale, determining if the time is approved (or not) and then rectifying. 

The "approval" could be as simple as "hey, PM, person X is going to assist on project Y, can we add them to the project?", etc. 

FWIW: I'm concerned that this could add more controls and additional/uncomfortable overhead for folks. I'm also concerned that we could potentially run into budget issues as well. This is where the conversation stemmed from.

**Comment by seanherron** [comment]
So, I'll be totally honest here - I think we need to draw a very strong line that Tock cannot be the tool by which we set policy or culture. If we're finding people are charging time to projects without the knowledge or approval or whatever of the product lead, then that is a problem that is rooted in the authority of the product lead to manage time spent on the project, not with how it is accounted in Tock. 

Tock can hopefully be a means for a product lead to discover such an issue early on, but should not be used as a gate by which we block or allow individuals to do work at 18F. At least in my opinion.

**Comment by russu** [comment]
I'm not suggesting we set culture, by any means. I'm suggesting that we make tracking budgets something a bit more streamlined. Given that we're rapidly approaching Dunbar's Number, it's getting increasingly difficult to maintain all the connections, and it's not always a simple task to control who adds time to which project. 

That said, I'm not disagreeing that we shouldn't use it to set policy, either. I see plenty of flaws with what was suggesting. 

===

Anything accepted via Intake, etc. probably should have a PM allocated to take on the projects. I don't think that we technically have PMs on all the projects, correct? That's a bigger discussion and I'm not trying to drive us off the rails, however, people who aren't living in the PM role don't always have the same experience that could help them with the controls that they need to have in place. This *could* help that.

===

This is/was a fairly selfish request on my part since I know what I'm taking on, and I'm considering what I think will be my own overhead here more than "everyone else" (however, considering it might be useful for others, too). 

That's my nickel. Thanks for listening/reading!

**Comment by seanherron** [comment]
I'd be curious about the thoughts of @jroo on this matter
