### ISSUE TITLE
cloud.gov shared database deprecation

### ISSUE THREAD

**Issue by cantsin** [18F/tock#1449]
We have a list of shared database instances (`shared-psql`) ​that we need to shut down or convert to dedicated instances since `shared-psql` is [going away](https://cloud.gov/2022/04/25/deprecation-notice/) -- see [RDS service documentation](https://cloud.gov/docs/services/relational-database/#access-the-data-in-the-database) on how to export/restore to a micro or small database instance.

## Production

- Remove `tockdb-new`
- Remove `tockdb-*-20*` (20180508, 20161215, 20161212)

## Staging

- Convert `tock-database` (we use this for staging, still)
- Remove `tockdb-old`

These need to be shut down or converted by **August 31 2022**

In addition, we want to update the documentation: `backup-and-restore-database.md` and `deployment-process` refer to `shared-psql` still.

**Comment by mgwalker** [comment]
## 1. Create the new database

We can do this first to minimize how long Tock is down. We'll rename it later,
but for now we don't want a name conflict.

```sh
cf create-service aws-rds small-psql tockdb-new
```

Creating the database service can take several minutes. You can check the status
by running `cf services | grep tockdb-new`. Wait for the status to change from
`create in progress` to `create succeeded` before continuing.

## 2. Take Tock offline

For real, stop Tock. We don't want data being changed while we're trying to
migrate it. The migration should only take a few minutes, but still, best to do
this part outside of key Tock times.

There are two ways to go here. In one case, you'd push up the maintenance page
and make it to the Tock URL so that the URL still shows something. The other
option is to just take Tock away entirely, in which case the URL won't resolve.
The latter is preferable.

```sh
cd tock/maintenance_page
cf push
cf map-route tock-maintenance tock.18f.gov
cf unmap-route tock tock.18f.gov
```

Now the Tock URL will resolve to the maintenance page.

## 3. Dump the current database to file

The easiest way to dump the current database is using the
[`connect-to-service`](https://github.com/cloud-gov/cf-service-connect) plugin
for cf-cli. After logging into the cf CLI and selecting the appropriate org and
space:

```sh
cf connect-to-service -no-cli tock tockdb
```

This will create an SSH tunnel for you through the Tock app into the database.
It will output the credentials you'll use to connect to the database. Note that
`connect-to-service` stays open, so you'll either need to background it or open
a second terminal tab/window to continue.

Next, use [`pg_dump`](https://www.postgresql.org/docs/14/app-pgdump.html) to
dump the contents of the database to a file. Make sure your `pg_dump` version is
equal to or greater than the Postgres version of the target database, regardless
of the version of the source database. `pg_dump` can dump from older versions
and restore into equal or older versions. It cannot do anything with newer
versions.

Use the credentials output from `connect-to-service` to populate the Postgres
connection URL:

```sh
pg_dump \
  -F c \
  --no-acl \
  --no-owner \
  -f tock.sql \
  postgres://<username>:<password>@<host>:<port>/<name>
```

> * `-F c` outputs a custom format suitable for `pg_restore`
> * `--no-acl` disables output grant and revoke commands
> * `--no-owner` makes sure the output is not owned by a particular user; this
>   way, ownership is inferred when the restore is run
> * `-f` outputs to a file; `pg_dump` writes to stdout by default

This make take a few minutes because the Tock database is pretty big. Once it's
finished, you can return to the tab/window where `connect-to-service` is running
and terminate it with `CTRL+C` to shutdown the SSH tunnel.

## 4. Switch which database Tock is bound to

```sh
cf unbind-service tock tockdb
cf bind-service tock tockdb-new
cf restage tock
```

The updated bindings don't take effect until after Tock is restaged.

## 5. Reconnect to the database service

```sh
cf connect-to-service -no-cli tock tockdb-new
```

Remember to either background the process or switch tabs/windows.

## 6. Drop the database

When Tock restages, it will create an initial database from the Django
migrations. That will include a bunch of constraints that restoring the dumped
database will violate. Instead of trying to deal with that, we can just drop the
newly-created database entirely.

When connecting with the `psql` CLI, target the `postgres` database rather than
the one to be deleted. You can't delete the database you're currently connected
to, so... don't connect to it.

The credentials and database name are provided by the output of the
`connect-to-service` command from the previous step.

```sh
psql postgres://<username>:<password>@<host>:<port>/postgres
DROP DATABASE <name>;
CREATE DATABASE <name>;
```

## 7. Restore data into the database

Once the database is dropped and recreated, it's ready to be restored:

```sh
pg_restore \
  --no-owner \
  --no-acl \
  --dbname postgres://<username>:<password>@<host>:<port>/<name> \
  tock.sql
```

## 8. Terminate the SSH connection one last time

Back in the tab or window with `connect-to-service` running, use `CTRL+C` to
terminate the process and close the SSH tunnel.

## 9. Bring Tock back online

```sh
cf map-route tock tock.18f.gov
cf unmap-route tock-maintenance tock.18f.gov
cf delete tock-maintenance
```

## 10. Fix up the service names

We want to rename the database services so that the Tock app can still be bound
to a service named `tockdb`, so we don't have to update any manifests or build
steps. Renaming a service does not affect its current binding to an app.

```sh
cf rename-service tockdb tockdb-old-shared
cf rename-service tockdb-new tockdb
```

All done! Now you can clean up any older services that you need to get rid of.

**Comment by cantsin** [comment]
I think we are almost done here? I checked prod/staging, and we have a couple of `shared-psql` instances in staging that I think we can safely remove. 

Other than removing these two instances, I think the last thing we could do here is to update the documentation. The above is :Amaze: -- much better than our current documentation -- and we probably want to save these notes for posterity. What do you think @mgwalker ?

**Comment by mgwalker** [comment]
I'll drop those database instances in staging and then work on porting this notes over.

**Comment by mgwalker** [comment]
There are also four `shared-psl` in prod. I don't know what they are, but three of them were created 5.5 years ago. The current `tockdb` reserved instance was created in 2020, and there's one that looks like it was used for pentesting and can probably be deleted and recreated in the future if we do pentesting again?

**Comment by mgwalker** [comment]
Deleted 3 of the shared database services in prod. The last one can't be deleted because the underlying database itself is gone so the `delete-service` command fails. We can either ask cloud.gov support to help, or we can wait until shared databases are deprecated and it'll probably go away on its own then. I recommend the latter. 🤷🏻‍♂️
