### ISSUE TITLE
Clarify authentication process

### ISSUE THREAD

**Issue by janearc** [18F/tock#42]
I was told that I would be logging in to MyUSA, then I was told I would be logging in with Google, then it asked for permissions, etc. – all this was confusing because I wasn't sure where the authentication was coming from and going to. If MyUSA is pulling my Google credentials, it would be nicer for me (this is my second-to-last timecard; consider new employees or people unfamiliar with the workings of the backend) if it explained "MyUSA needs your Google credentials to continue. Click to continue to Google to authenticate" and then a subsequent "oh hi jane thanks for authenticating to Google, MyUSA now knows you are Jane foo of organisation Bar let's timesheets for you, k?" or something. It was six clicks from the link in patrick's email to the interface to fill out the time card and all of them were just clicking through authentication proxies.

**Comment by mbland** [comment]
Might be more apropos for the MyUSA folks to address this.

cc: @jackiekazil @adelevie @yozlet @esgoodman @mkhandekar

**Comment by adelevie** [comment]
Hey, @janearc, thanks for the feedback. I'm sorry that the process was confusing. To help me better understand the issue, you'd like to see on the very first page (e.g. 18f.hub.us/tock) some type of indicator that you'll be asked for Google credentials? 

For whatever it's worth, Google credentials aren't required here. I use the "Connect with email" option. Perhaps we should be clearer about that? For Hub purposes, you still need to enter your GSA email address, which is then checked against an email whitelist. So we have two different ways to verify that you control the email address [fname].[lname]@gsa.gov.

**Comment by esgoodman** [comment]
@janearc Is this the basic sequence of events you encountered?:

Click link in email -->  the page with the MyUSA button
Click the MyUSA button
Hit sign-in with email --> email address window
Enter email and hit submit 
Go to email
Click access link --> you are logged in

Our initial worst-case login scenario for MyUSA login involved three clicks. It sounds like you hit that scenario, but because of some unexpected wrinkles with the Tock integration, a few more clicks got added and the usual explanation stripped out. 

@adelevie I can walk you through what I think is happening here. There might also be a bug involved -- I have been getting some odd events while experimenting with the Tock login.

**Comment by mbland** [comment]
Little extra context "Tock login" is going through the same `google_auth_proxy` instance as the rest of https://hub.18f.us/.

@esgoodman, aside from the logout issue noted in 18F/hub#245, are there any more login issues you think might be auth proxy-related?

**Comment by esgoodman** [comment]
@mbland Well...I got a weird 403 Invalid Account error message after trying to sign in with my personal Gmail account once, but I hesitated to file an issue because I can't seem to replicate it. 

Here's the URL I got with the 403: 
https://hub.18f.us/oauth2/callback?code=1e469d84a30fb1952462ca16e377a74ea5d9b1af7e7fa2c8cf836307aaa98add&state=%2Foauth2%2Fsign_in

**Comment by seanherron** [comment]
I'm going to close this as I don't believe there is further Tock discussion here - if there's a desire to improve upon this further, please take it to the hub or myusa repos :)

**Comment by jackiekazil** [comment]
@egoodman -- is there a ticket for this in the myusa repo that you can link
to about this work for others reference?
