### ISSUE TITLE
Authentication setup for API

### ISSUE THREAD

**Issue by jessieay** [18F/tock#458]
At the moment, there is no auth for the Tock API, eg: https://tock.18f.gov/api/projects.json

We should create and document an auth system for accessing the Tock API.

Pieces of this:
- Create a system of keys that can be created and deleted via the Django admin UI
- Keys are associated with a particular user or application (so we know who they are for)
- Keys can be used (sent in header?) to access any API endpoint
- Document how this auth works in the `README`

this will help us fix: https://github.com/18F/micropurchase/issues/951

**Comment by toolness** [comment]
We should probably use `django_rest_framework`'s [`TokenAuthentication`](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) scheme for this.

For applications like Micropurchase, I'm wondering if it'll actually be most expedient to make a user for them that simply doesn't have an email address associated with it (so no one can "log in" as it), but that does have permissions and an API key.  Does that sound reasonable?

**Comment by jessieay** [comment]
sure, that's fine. whatever works on your end works for us!

**Comment by toolness** [comment]
Erm, I'm very confused now.  I thought that this app was migrating to a system where Django was handling all the auth, as per #446 (which was mysteriously closed), but it looks like the new auth system works much like the old one, where something in front of the Django app is setting an `X-Auth-User: firstname.lastname@gsa.gov` header.  As with the MyUSA-based auth, this makes it very difficult to use a completely different token-based scheme on the `/api/` endpoints unless whatever is sitting in front of the Django app is configured specifically to pass through all requests that start with `/api/`.

@batemapf any idea why this new auth scheme is in place, rather than #446?

**Comment by batemapf** [comment]
ah yes, quite a mysterious close @toolness. meant to drop a comment in there referencing #456. we could certainly reopen and rework the authentication backend. however, setting up the UAA proxy to forward header info (X_AUTH_USER:...) to Tock is just simpler at this point...

...except for setting up an authenticated API :-)

Here is (roughly) what i am thinking:
1. set up a simple token-based API authentication system with a single token per user. could save this right in the employes.models.EmployeeData class and tack on a custom save() method to delete the token when the employee is `active=False`
2. require usage of that authentication system for all /api/ URLs.
3. create an alternate route to the app (say, tock-app.18f.gov/api/) that _is not_ behind the UAA proxy. the route would be limited to the /api/ path, so no other parts of the app could be accessed.
4. generate and supply tokens to users upon request.

**Comment by jessieay** [comment]
@dlapiduz removed the API route for now https://18f.slack.com/archives/tock-dev/p1474322226000096

What are next steps on this?

**Comment by batemapf** [comment]
closed via #465
