### ISSUE TITLE
Shift reporting period to Saturday through Friday

### ISSUE THREAD

**Issue by fureigh** [18F/tock#510]
Now that our deadline for logging time in Tock is every Friday, it'd be great to update this system to match, as people do sometimes need to log weekend hours.

**User story:**
As a staff member logging time in Tock on Fridays, I want the presented reporting period to match the period on which I'm reporting so I can be confident I'm reporting my time accurately rather than, say, having to make projections about Saturday or carry Saturday's time into next week.

**Current behavior:**
Tock shows me `[Sunday,] October 2, 2016 to [Saturday,] October 8, 2016`

**Desired behavior:**
Tock shows me `[Saturday,] October 1, 2016 to [Friday,] October 7, 2016`

**Technical questions:**
- Dare we/can we have one week that goes from Saturday to Saturday?
- As we currently log time on a weekly, not daily, basis, this would presumably have implications for reporting.

**Comment by hollyallen** [comment]
Our pay periods are two weeks long, Sunday to Saturday, so the current behavior is correct. The deadline should be end of Saturday, as you say Fureigh. I believe nobody really considered having a weekend deadline because it may imply one *should* be working on a weekend, which isn't true. I have heard that as long as your timesheet is submitted before Ops starts work on Monday then all is well, which summarizes as Friday very easily for most folks. Should that be made more clear?

**Comment by sfvictor** [comment]
Can we merge this with #525 I've made updates to a request made by Maya and I believe it covers everything (not sure if this is proper method, still figuring out github).  thanks vv

**Comment by hollyallen** [comment]
Maybe! In #524 you referred to Saturday work as authorized overtime, but sometimes Saturday work isn't overtime but pre-arranged normal time shifted from the normal workdays.
