### ISSUE TITLE
Tock UID

### ISSUE THREAD

**Issue by rooneywp** [18F/tock#535]
**Issue:** We need a way to uniquely identify a person that is standard across all data sources (Tock, Float, Talent database, etc.)

My suggestion here is to make this the employee's email address. Email is a practical UID and since it's something we can predict, we aren't dependent on a federal system generating the data. The reconciliation required should really only impact the Talent database since we likely wouldn't be creating an entry in any other system until the official UID was assigned.

An alternative would be to generate a 18F specific employee number for each person, which would remove the need for validation but isn't by itself a practical piece of information and adds a new field to be created and tracked. CHRIS does issue and employee number but the processing time required to get that number prevents us from being able to have the UID for personnel tracking prior to it's creation in CHRIS.

**Comment by batemapf** [comment]
@rooneywp completely agree that UID should be email address. Tock presently generates a user's username based on the local portion (the part before the @) of an @gsa.gov email address. It receives this data (the raw email address) via our authentication system. the only issue we have encountered with this approach is when a user changes their official email address. when that happens, a second account is automatically created and needs to be merged with the original account. since this does not happen very often, it is handled manually.
