### ISSUE TITLE
Utilization Report: Please show non-billable also

### ISSUE THREAD

**Issue by hollyallen** [18F/tock#542]
It would be helpful to me to see the Engineering Chapter "exempt" staff in the utilization report. Some of us do bill hours occasionally, and this is the only view in Tock where I can see folks filtered by chapter. Thanks!

**Comment by batemapf** [comment]
@hollyallen this is an easy tweak. however, before implementing, would you mind checking with your supervisor colleagues to confirm that they will not be bothered by all of the additional names of "exempt" employees? immediate impact will be more stuff to scroll through, and possibly a tiny (probably not noticable) decrease in performance.

**Comment by rdpiazza** [comment]
I don't have an issue with this since Product's utilization report already shows a few people with 0 hours, like Claire (an ELP) and Clara (on detail from USDS).  The point raised about performance touches on a related feature I was thinking of that would probably be helpful for this:  showing chapter performance totals for both staff who are primarily billable and the team at large.  Would be helpful to see that primarily billable people average, say, 81% billable even if the team at large (with exempt staff and details) average, say, 70%.  Would also give a more accurate number of total hours for the team per week if some of the exempt staff are able to bill.

**Comment by batemapf** [comment]
@rdpiazza could definitely do total rows for team at large plus components of the team. any idea where i get the staff "types", or is it just "exempt" and "billable"?

**Comment by rdpiazza** [comment]
Hmmm...I'm asked to fill in spreadsheets frequently to flag people as Primarily Billable, Partially Billable, or Exempt but I'm not sure how it's stored in Tock or other systems you could access via an API.  Maybe Bailes or Talent would know?
