### ISSUE TITLE
Automatically open this week's timecard

### ISSUE THREAD

**Issue by mgwalker** [18F/tock#628]
As a person who needs to track their time, I want the current reporting period to be open on Monday morning so that I can track my time accurately in Tock from the beginning of the week instead of having to either use a separate tool or guess at it later.

**Comment by batemapf** [comment]
@lsgitter Are you cool if we auto-create reporting periods? I'm thinking whoever the first user is to open Tock after the close of the last reporting period (say, @mgwalker first thing on Monday morning 😄) will trigger creation of a standard reporting period. An admin user would still have power to create / amend / delete reporting periods, as well as attach a holiday as needed. We could also add an exception in to _not_ autocreate during the last and first weeks of the fiscal year (since those get a bit wonky).

Thoughts?

cc @joshuabailes @abrouilette

**Comment by lsgitter** [comment]
@joshuabailes is the one who uses them so if he is fine with it, I am.

**Comment by batemapf** [comment]
Closed via #637.
