### ISSUE TITLE
Unexpected UI behavior: Mouse scrolling changes hours

### ISSUE THREAD

**Issue by pburkholder** [18F/tock#659]
![out](https://user-images.githubusercontent.com/1211146/29752586-cffcb67a-8b15-11e7-8581-8bc2c6c9b222.gif)

If I touch my mouse scroll at all while entering hours it will increase/decrease
the hours.

This UI feature continually confounds me: I enter my hours, then I intend to scroll to the next
form entry, and my number of hours for that field increases by some
arbitrary amount.

Can you please remove this feature?

**Comment by ccostino** [comment]
I did a bit of research and this appears to be due to the browser's default behavior/handling of the `number` input form type.  The most common solution I found was to just disable the event on that input element type, so when there's a moment we'll take a look to see if that'll help alleviate it.

Just to confirm, @pburkholder, this is with a mouse with a scroll wheel that you're seeing this behavior with?  Or is it a magic mouse with the swipe action?  I ask because I can kind of simulate the behavior with the touch pad on the laptop, but if I just move the cursor out of the field (even if it still has focus), it goes back to scrolling the page itself.

**Comment by pburkholder** [comment]
@ccostino Thanks for the response. I've had this happen with a magic mouse with swipe, so what you describe with touchpad is what I observe with the magic mouse: "if I just move the cursor out of the field (even if it still has focus), it goes back to scrolling the page itself."

**Comment by ccostino** [comment]
Okay, this bit me today and I almost missed it!  Not sure how as I thought I moved out of focus of the form element, but I noticed a weird thing too where the element comes back into focus after an action.  I definitely share your pain about this.

**Comment by ccostino** [comment]
This will be fixed with PR #662!
