### ISSUE TITLE
Update Django to the latest version

### ISSUE THREAD

**Issue by annalee** [18F/tock#699]
Per Django's update docs, we'll need to update to 1.11 before updating to 2.0.x.

**Comment by ccostino** [comment]
There is at least one known issue with this update that has prevented it from happening sooner:  The timecard form breaks with the move to 1.11 due to a change in how the initial form data is serialized and sent to the page.  In 1.10, the JSON comes through as expected and we're able to initialize the form properly, but in 1.11, we see the raw JSON being printed on the page and I haven't been able to figure out where the breakdown is in terms of marking something safe or escaping something.

There might be an interaction going on with the [Chosen JS library](https://harvesthq.github.io/chosen/) that also needs to be accounted for, so that could be another piece to check.

**Comment by toolness** [comment]
Ok, I've filed #740, which gets us to 1.11, which is actually a [LTS release that will be supported until at least April 2020](https://www.djangoproject.com/weblog/2015/jun/25/roadmap/).  Do we think that 1.11 is enough for ATO-hood, or is 2.0 required?

**Comment by ccostino** [comment]
Ah that is a good question, @toolness.  @rogeruiz what do you think, should we stick with just the LTS releases for the purpose of ATO activities, or do you think it's okay to go with the latest stable?

**Comment by rogeruiz** [comment]
I think this is good to close for now. We're good for now.
