### ISSUE TITLE
eRegs team members prefilling incorrectly. 

### ISSUE THREAD

**Issue by abrouilette** [18F/tock#718]
eRegs team members @rtwell, @thebestsophist, and @tadhg-ohiggins all had their Tock timecards prefill as FAITAS Foundation Engagement rather than the correct eRegs Phase 2. To the untrained eye the same error happening the same way three different times seems hopeful. (Though not as hopeful as how few people had a problem at all, for which ALL THE HIGH-FIVES.)

**Comment by cmc333333** [comment]
Same here, also on eRegs

**Comment by abrouilette** [comment]
@yowill?  @micahtaylor?  @toolness?

**Comment by micahtaylor** [comment]
@abrouilette I'm not on eRegs anymore. I am on login.gov. Mine is prefilling both. Talk about utilized! 

<img width="1062" alt="screen shot 2018-02-06 at 9 20 34 am" src="https://user-images.githubusercontent.com/671894/35867245-ef5a129a-0b1e-11e8-9f8d-3c6fc5d0b873.png">

**Comment by toolness** [comment]
Yup, I am having the same problem--my last Tock pre-filled me for 40 hours on "FAI / FAITAS Foundation Engagement" but I had to change it to OMB Policy Library.

**Comment by tadhg-ohiggins** [comment]
This week my pre-fill is different but still incorrect, and also I have both `670 - 18F / FY18 Out of Office` and `749 - TTS Operations / FY18 Non-Project Work`.
The pre-filled 40 hours are set to `751 - FY 18 / TTS Operations / Out of Office`, which AFAIK I've never logged time to (unless I did so by accident).
Screenshot:
![image](https://user-images.githubusercontent.com/2626258/36055531-f83aa8f8-0db1-11e8-874f-4414e71aef45.png)

**Comment by ccostino** [comment]
@tadhg-ohiggins the items that show up that aren't pre-filled (no hours) are pulled from the previous week's timecard.  You're saying that you didn't enter any hours for those items the previous week?

**Comment by tadhg-ohiggins** [comment]
@ccostino As it turns out I seem to have accidentally entered some hours to 751 the previous week—but *not* to 749.
Also, I definitely didn't enter any hours on 751 for the period starting 2018-02-04 (last week), but this week `751 - FY 18 / TTS Operations / Out of Office` is again showing up with 40 hours auto-filled.

**Comment by ccostino** [comment]
@tadhg-ohiggins okay, that at least explains some of it!  The reason you see the prefilled 40 again is because there is a prefill record with that information that we need to adjust/remove.

Speaking of which, @lsgitter and @abrouilette, who should be the one to make these prefill adjustments for these folks?

**Comment by abrouilette** [comment]
Excellent question.  Do we want to adapt the Tock Change Form to include incorrect prefills?

**Comment by ccostino** [comment]
Yes it can, closing!  Sorry for the confusion, everyone!  We hope to get this sorted out in the near future. :-)
