### ISSUE TITLE
Filter projects in other orgs out of dropdowns

### ISSUE THREAD

**Issue by toolness** [18F/tock#753]
As an 18F employee, I worry about accidentally choosing another organization's version of a time category instead of my own--for example, I worry I might select "TTS Operations / Out of Office" instead of "18F / FY18 Out of Office".

I'm not sure if Tock knows I'm part of 18F, but if it does, it'd be cool if it could cull out the projects (or at least the OOO's and other common categories) from the dropdown so I don't accidentally select them.

**Comment by ccostino** [comment]
Hey @toolness, Tock does know about organizations now!  There is an `Organizations` model tied to the `EmployeeData`. :-)  I don't know that we have it filled in yet, but if not this is an operations/admin question.

However, we need to be careful about this a bit because you could be detailing or assigned to a project outside of your organization, e.g., you're working on an acquisitions project but are in 18F or vice versa.  For things like the out of office (and holiday prefills) though, this would be nice. :-)

**Comment by adunkman** [comment]
Closing for now since we haven’t moved on this feature and we now use a consolidated out of office line, reducing the chances of mis-tocking.
