### ISSUE TITLE
Implement org restrictions on our tock lines

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#853]
Could we implement org restrictions on our tock lines? We have had  issues with CoE folks accidentally selecting 18F lines and 18Fers selecting cloud lines.

Thanks to the efforts of @amymok and Keia, all users should be associated to an org now, and we should be able to see those orgs to ensure they're correct, so we should know which org a user belongs to, so that we can show them only the tock lines for that org.

We can probably do this with a simple `limit_choices_to=user.org` or something similar, when we build the Tock input form. 

However, we'll want to NOT implement that filtering in the admin, so in the rare occasions someone tocks cross-org it can still be handled manually.

*We'll know we're done when*
* We've double-checked that org is a required field on user, since we'll now be controlling logic based on it.
* All tock lines are tied to an org, if they're not already (Keia can probably assist on this one)
* User-facing form filters tock line choices based on the user's org
* Admin form still works as before.
* Tests are written

**Comment by ccostino** [comment]
The one situation I can think of where orgs may not be enough is if someone is doing work on a project that is within a different org (meaning an entirely different P&L under the hood, which is what an org should ultimately be tied to when the financial processing takes place).  Real example:  someone in 18F is working on something for cloud.gov, or (hypothetical example) someone within cloud.gov is helping with something in 18F.

However, due to the policies in place that require labor agreements even between the organizations with TTS, there is a solution to this that is process-oriented as opposed to code that has to be written.  Using this example, which is , there are Tock lines created specifically for folks in 18F who would bill to cloud.gov, or to Kessel Run, and there are cloud.gov specific lines for the folks actually on the cloud.gov P&L.  There is no Tock line for cloud.gov folks to work on anything 18F-related because there is no labor agreement in place in that direction.

If anything, some extra guidance needs to be written with this and a concrete policy put in place that clearly states that in order for a person in one org to work on a project in another org, there needs to be a specific Tock line available that exists within the user's org that they can Tock to, and only this Tock line would show up as an option to them.  We should already be doing this, but I don't think it's explicitly written down anywhere.  I'm not sure where this should ultimately exist, but at least some reminders in Tock itself would be a helpful thing.

@abrouilette, @acolter, does this make sense and do you have any other thoughts around this?  Is there anyone else that should be flagged on this?

**Comment by acolter** [comment]
I think it makes sense to keep track of who works for which organization in Tock. I worked with Keia earlier this week to make sure people in Tock accurately map to their P&L (18F, cloud, login, COE, TTS, OA, etc.) Doing this helps me identify when there is a mismatch between a person's P&L and the project that they're tocking to. 

However, there are legitimate reasons why someone might cross P&Ls. Someone in 18F might bill to cloud, etc. I don't think there's any reason why someone from the COEs or TTS would bill to an 18F project (or, more likely, 18F Out of Office) but I don't know that this happens so frequently that we have to actively prevent it. 

I've been reviewing the tock reports each Monday to catch the mis-billers. A few weeks ago I might ask Keia to make dozens of changes. This week there was a single change. While we have minimal errors, I think we should work to better communicate expectations rather than straight up preventing people to Tock to the wrong thing.

But I'm happy to hear arguments to the contrary.

**Comment by tbaxter-18f** [comment]
Well, I'm always a fan of doing nothing if it will achieve the desired results, so if the work that Amy and Keia already did to ensure every user had an org attached to them is sufficient, then I'd vote to just close this as unnecessary.

**Comment by tbaxter-18f** [comment]
OK, not hearing any arguments otherwise, I'm going to close it out. As always, if we change our minds we can reopen it.
