### ISSUE TITLE
Update nav to differentiate user and administrator actions

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#868]
To make the Tock nav more logical, we'd like to differentiate between user actions (reporting time, finding the override form, logging out) and reports and admin actions that users are generally not so interested in. 

Discussion took place in this google doc:  https://docs.google.com/document/d/1lWFJggjjp7Ue2FbJGaxswGiXhuD4f6tUq37NqfJOEWE/edit?ts=5c353be2#

Where we landed on moving the administrative actions to the upper right, as the attached (very rough) mockup shows:

![screen shot 2019-01-08 at 4 39 04 pm](https://user-images.githubusercontent.com/32077682/50902598-efe6e780-13e0-11e9-8a55-a423236a14e6.png)

We should also add a link for “file time report” -- currently, if you follow another nav item you have to click on the 18f logo to get back to the ability to file your timesheet. This doesn’t make a ton of sense since the app doesn’t really have a homepage per se; it has different sets of actions available in different places. All those actions should be enumerated on every page.

Note that mockup is just a mockup and should not necessarily be construed to represent the desired final state.

Note that there are some Nav items that aren't visible to all users, and we'll need to be sure to account for those.

**We'll know we're done when**
* "File time report" link is added
* Navigation is modified similar to depiction

**Comment by tbaxter-18f** [comment]
It may make a lot of sense to tackle this and #867 in parallel

**Comment by tbaxter-18f** [comment]
Also, if we've got some writers with some spare time on their hands, getting a bit clearer and more consistent with the language in these nav links might be nice.

**Comment by jenniferthibault** [comment]
@tbaxter-18f what are the nav items under Admin that aren't visible to all users? I took a crack at this with some content designers, but missed that one

**Comment by tbaxter-18f** [comment]
Assuming I have full permissions (and I think I do), I have 

* A link into the site admin
* Create reporting period
* Bulk timecard CSV (may be available elsewhere, I'm not sure)

There's also a "supervisor" tab with a single item under it to "utilization reports"

I think the other links are all public.

Personal opinion: I don't think we have enough links that we necessarily need to put any of them behind dropdowns.

**Comment by jenniferthibault** [comment]
Here's an initial direction that was even ✨blessed✨ by a few of our NYC-based content designers in an informal feedback session. The goal was to use matching format & point of view:

**Nav item microcopy**
`Verb`: `noun` with (second person, "you"). Recent hires gave feedback that they get an orientation to Tock week 1,  so they learn immediately that "to tock" is a verb here :) Since this is internal, it felt good to have that bit of fun here, but a more austere backup for the first item is `Report your time`. We can also group similar actions with the dropdown item for summary views.

**Styles**
This uses styles from the [18F site](https://18f.gsa.gov/) to create separation between the main nav and a utility nav (for log out & admin actions)

![screen shot 2019-01-28 at 5 43 51 pm](https://user-images.githubusercontent.com/11636908/51871429-54340180-2324-11e9-9585-b26d68de24c4.png)

The only thing I didn't bring in was the "Supervisor" tab since it seemed like the "Review summaries" group might capture this action? Let me know if not — might be worth investigating who uses it & how before putting a lot more into the info architecture

**Comment by tbaxter-18f** [comment]
Thanks @jenniferthibault! I think this looks really good. A couple of questions, though:

1. In my head at least, I saw us separating out the two nav actions according to the two types of users:
- General users, who want to be able to tock (or revise a tock) and log out
- Admin users, who mostly want to view or download different reports, or go into the site admin.

Can you elaborate a little on why we're taking a different direction and the thinking behind it? Not that I dislike it, but I would like to understand the thinking more.

2. Why the language change from "reports" to "summaries"? 

Thanks!

**Comment by jenniferthibault** [comment]
Glad to!

On a different direction for 
> separating out the two nav actions according to the two types of users

The thinking behind including links to viewing data in that main nav is that  people other than admins access those. And grouping it in the main nav makes it clear that the data is there for all who are curious, not just for management. This is an untested hypothesis, but given that transparency is important to 18F, I like the sentiment of not moving it out of the main area. Additionally, someone from management who is frequently using the summaries should be able to access it in the same space as other primary actions.

If additional pages or features are added later, I totally agree that there might be a time when we should separate navigational spaces into "Do the thing!" and "Find data on all the things!" — but doesn't _quite_ seem like we're there yet to me. 
But again since we're all working without real usability research, 🤷‍♀️ 


> Why the language change from "reports" to "summaries"?

We started with `Report your time` instead of "Tock your time". "Summaries" became the best grouping word to disambiguate the report individuals file every week vs the bigger picture data capture. Feels helpful to keep this separation.

**Comment by tbaxter-18f** [comment]
On the first one, got it. That makes a lot of sense. On the second, I think we should keep "reports", since they really are full reports, including downloadable CSVs, and I think since we're keeping the "tock" verbiage, it's sufficiently differentiated and clear.

From the design side, I'm happy! Thank you! 

Now we just have to build it :-)

**Comment by tbaxter-18f** [comment]
@hbillings in your opinion, should we block this on the USWDS uplift?

**Comment by hbillings** [comment]
@tbaxter-18f yes, I think so. That update should be ready to go by the end of this week! 

Also I miss @jenniferthibault.

**Comment by tbaxter-18f** [comment]
I thought so too. I think it will be pretty easy _after_ those changes are rolled in, but would be messy before.

And 100% agree on missing @jenniferthibault

**Comment by jlthibault** [comment]
💞👻💞

**Comment by Jkrzy** [comment]
I _think_ this was resolved by @hbillings in https://github.com/18F/tock/pull/1132.

😍 
<img width="1015" alt="Screen Shot 2020-08-07 at 12 48 43 PM" src="https://user-images.githubusercontent.com/3485564/89668825-680edb00-d8ac-11ea-9380-0b3a915e1a26.png">

Also 👋 @jenniferthibault 👋 , we still miss you 😄
