### ISSUE TITLE
Entry (home) page organization

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#869]
From https://docs.google.com/document/d/1lWFJggjjp7Ue2FbJGaxswGiXhuD4f6tUq37NqfJOEWE/edit?ts=5c353be2#

- “Welcome to tock” is unnecessary and competes for attention with “reporting periods to fill out”
- “Reporting periods to fill out” overshadows the actual things you can do on the page
- There’s lots of help in the handbook, but it’s not referenced anywhere.

### We'll know we're done when:

* “Welcome to tock” is struck
* "reporting periods" header is set in a more appropriate size
* Additional emphasis given to reporting periods you need to fill out
* Sidebar is created with a link to handbook and other persistent quick-reference points

Bonus: can we figure out how to draw additional attention to any past due reporting periods?

See the Google doc under "Entry page" for a rough visual representation

**Comment by tbaxter-18f** [comment]
This is another case that maybe we should talk with content folks about

**Comment by jenniferthibault** [comment]
Pairing with the update in #870 , here's a styled concept for the home page:

![tock - home - large](https://user-images.githubusercontent.com/11636908/52062559-ba946c00-253e-11e9-86c5-e2b06b05e7cf.png)

________

**Goals:** 
- Make a separate space for finding initial instructions and supplementary help about Tock. (I pulled links from @hbillings's mockup, but focused on directions instead of text and used the sidebar link list pattern from the[ 18F site](https://18f.gsa.gov/blog/) )
- Reduce the text in the date list for easier scanning
- Create more visual distinction between the week's current timesheet and any that are overdue
- Make it easier for a time submitter to find previously completed weeks, so that they can reference project codes and hourly breakdowns more easily (this was a great piece of feedback from my critique group when I showed it to them!)

Differing from Heather's mockups, I'm keeping all supplementary info on the right side of the layout in order to keep the primary action (filling out timecards) the higher in the visual hierarchy.

Looking forward to your thoughts!

**Comment by tbaxter-18f** [comment]
We'll need to look into how we might implement Recent weeks. Shouldn't be problematic, although I do think we'd need to make them read-only.

Should the sidebar design here and in the form page be the same?

**Comment by jenniferthibault** [comment]
Yeah figured there was a thing or two to parse out here.

I was _hoping_ we could use these views for each user: https://tock.18f.gov/reports/2019-01-20/jennifer.thibault/ 
No need to bring them to the time report screen, just link to what they submitted in this format. If that's the case, maybe a first step would be to show only the three(totally arbitrary number) most recent completed reports and drop the link to "previous reports" since that would need some design/engineering work for revealing additional reports. 

Is that totally off-base?

**Comment by tbaxter-18f** [comment]
That makes total sense and seems like a great idea to me!

**Comment by tbaxter-18f** [comment]
Thanks Jen. That's excellent context. So, on the form page, if it morphed over time to more of a list of short phrases we'd want to consider pulling the list-type styling instead, right?

**Comment by jenniferthibault** [comment]
Yup exactly — use this format with lists:
![screen shot 2019-02-01 at 9 56 15 am](https://user-images.githubusercontent.com/11636908/52130278-ba13d800-2607-11e9-829b-e0ef03e20b28.png)

**Comment by tbaxter-18f** [comment]
Blocked on #867
