### ISSUE TITLE
Time entry page organization

### ISSUE THREAD

**Issue by tbaxter-18f** [18F/tock#870]
From https://docs.google.com/document/d/1lWFJggjjp7Ue2FbJGaxswGiXhuD4f6tUq37NqfJOEWE/edit?ts=5c353be2# we have identified several potential areas of improvement. You can see a rough mockup under "Time entry page"

### We'll know we're done when:
- Sidebar is created with a link to handbook and persistent quick-reference points
- Persistent and long-running notices should be moved into the sidebar. That top-of-page section should be for alerts related to the current time period, such as OOO reminders. (Note this may require some django work to differentiate the types of alerts)
-  Instructions about tock should be in the sidebar, where it is easier to reference while filling out the form.
- Submit and Save buttons should be differentiated. If Submit is bigger, don’t put them in line with each other.
- The notifications about which lines to not Tock to might be more effective if you see them as a reminder right before you save. Alternately, they could be moved into the instructions as well.

Bonus: If we can figure out how to only show the lines to not tock if we think the person did it incorrectly, that would be sweet.

**Comment by qmanderson1** [comment]
I’ll be pitching in along with a Visual Designer next week on of Tock's design issues. I’m hoping someone from the team can provide some context to help get us started. Here are a few questions I have: 

How did the proposed changes come about? Were they a result of user feedback? And if so, is there user research we would be able to review? 

Is there a sketch file with Tock’s UI elements?

**Comment by jenniferthibault** [comment]
Picking this up with @qmanderson1 and getting started tomorrow — @tbaxter-18f do you know who might be implementing the work from this issue? Is that you?

**Comment by tbaxter-18f** [comment]
Not sure yet. Might be me, might be @hbillings, or might be one of our other front-end wizards looking for something to pick up. Let me see if I can firm that up.

**Comment by tbaxter-18f** [comment]
Also, I meant to link these up before, but this one is pretty closely related to https://github.com/18F/tock/issues/869. Both are calling for reorganizing persistent info in a sidebar for quick reference and differentiation from "right-now" alerts.

**Comment by qmanderson1** [comment]
@tbaxter-18f @jenniferthibault and I have been putting together some options for a different layout but we have a question about the instructions that should be moved to the sidebar. Which of these is more aligned with the goal of the instructions in the sidebar? 

- Have instructions available in case folks need help 
- Ensure people read the instructions prior to completing the form

And if neither of those are on track please steer us in right direction. Thank you!

**Comment by tbaxter-18f** [comment]
I think what we're thinking -- and you can kind of see this in the mockups @hbillings put together, linked above -- is that the instructions in the sidebar would be more of a quick-reference, reminder sort of thing, and if there are instructions up top, that's reserved for Very Important Info For This Time Period You Must Read Before You Tock. Does that help?

**Comment by jenniferthibault** [comment]
Yep, thank you!

**Comment by tbaxter-18f** [comment]
Thanks Jen, I like the overall concept quite a bit. I would like to hear from the Accessibility Guild on any thoughts regarding relocation/removal of form labels. @nkkl can you weigh in?

**Comment by nkkl** [comment]
I think this is ok because we have a known, constrained audience at this point in time. As long as everyone in that specific audience is able to use it everything is gravy (and if they're not, they'll tell us). It's also a tool that people use regularly, not a thing that many folks are seeing for the first time ever.

I would consider modifying the first mockup – right now it signals that you've reached your 40 hour quota with a green outline on the hours box, which may not be clear to someone with color vision deficiency. I would not call it critical because our user base knows that they are supposed to add up to 40, but it wouldn't hurt to add a checkbox or something to get around that.

Things I would be broadly concerned about, if I were planning to take this to a broader audience:

- Does each element have an appropriate HTML label, so that it works as expected with a screen reader and other AT?
- Do users get disoriented when scrolling through a very large number of entries? If so, we may want to consider something like a sticky top label so that context is retained.
- Is necessary information lost when text is magnified and/or the page is zoomed in? If so, we may want to add the individual labels back in.

**Comment by tbaxter-18f** [comment]
Thanks for weighing in @nkkl!

I think my preference would be to retain visible form labels, both for a11y and for orientation on longer pages. @jenniferthibault would that be OK from your end?

**Comment by tbaxter-18f** [comment]
Blocked on #867

**Comment by jenniferthibault** [comment]
Here are the design files for this work that will be useful to any other designer picking up tock work [Tock-pages.sketch.zip](https://github.com/18F/tock/files/2998067/Tock-pages.sketch.zip)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
