### ISSUE TITLE
Admin Tab for newly added admins

### ISSUE THREAD

**Issue by saraheckert** [18F/tock#926]
As a newly added admin, I have the rights to update various features, but the admin button does not appear in my main tock menu.  I am able to use a workaround by copying the admin URL.  Thanks!
<img width="840" alt="Screen Shot 2019-11-25 at 8 53 53 AM" src="https://user-images.githubusercontent.com/42154564/69556035-53c6c000-0f61-11ea-9e07-e01d72e0ccf6.png">

**Comment by tbaxter-18f** [comment]
Thanks for logging this @saraheckert 

For anyone reading, in some very cursory looking, I think this is related to the permissions check we do to build the nav. We're checking for `is_superuser` but I think we maybe/probably should be checking for `is_staff` and then sort it out with permissions, since `is_staff` is usually the determining factor for getting into the admin. 

Totally open to other options. At any rate, see https://github.com/18F/tock/blob/master/tock/tock/templates/_navigation.html#L33

**Comment by Jkrzy** [comment]
This one is a bit of a rabbit hole...since I don't think its clearly defined anywhere when someone should be a superuser as opposed to just having admin access and fine grained permissions. Though there's definitely a divide in functionality and a handful of users where `is_staff and not is_superuser`.

For now, let's provide a nav option for _everyone_ that does have admin access.

**Comment by tbaxter-18f** [comment]
My opinions, for whatever they're worth, based on my understanding of general django concepts:

1. No one should be a superuser except Tock core devs
2. is_staff is conventionally the expected pathway to the admin

Not saying that's how we have to do it that way, just clarifying the expectations I'm coming to the conversation with.

**Comment by Jkrzy** [comment]
Agreed with that being the desired state, will take some audit/documenting/role updating to get there and this effort should also close out #873.

**Comment by Jkrzy** [comment]
Nav provided in #930, will continue audit/documentation/updating work in #873
