### ISSUE TITLE
Design tweaks to billable hours indicators

### ISSUE THREAD

**Issue by adunkman** [18F/tock#976]
A follow-up to https://github.com/18F/tock/pull/955#issuecomment-584203928, wanted to get this logged as an issue so we don’t lose it! 

/cc @igorkorenfeld

**Comment by igorkorenfeld** [comment]
Capturing the conversation with @adunkman today: 
The initial goal was to adjust the colors so the red circles didn't radiate against the blue, the alignment of the text labels above the circles was more balanced, and similarly that the "add item" button was aligned to something and didn't float in the blue field. An iteration that addressed these issues was this:

![Tock_Circles_E](https://user-images.githubusercontent.com/52677065/76127279-46dd5200-5fcf-11ea-9630-8acb5d17c95a.png)

I heard additional feedback from the product design team that the two circles were confusing. Based on a suggestion to use text in place of graphics, I mocked up the following:

![Tock_Circles_F2_02](https://user-images.githubusercontent.com/52677065/76127448-a76c8f00-5fcf-11ea-9688-4686f303880d.png)

Pairing with @adunkman we talked about exploring a way to make hour sums less tabular, and putting less emphasis on the the warning about billable hours, since folks may not have much control over that, whereas they do have control over the total hours. Some iterations from that discussion: 
![Tock_Circles_G](https://user-images.githubusercontent.com/52677065/76127655-311c5c80-5fd0-11ea-98c2-6539adeb66b0.png)

Adding the billable count back in:
![Tock_Circles_I](https://user-images.githubusercontent.com/52677065/76127672-3ed1e200-5fd0-11ea-9d55-051be86ef553.png)

After our talk I was able to get it to work on one line, though I think the "under" language will need to be revisited (perhaps the longer, but clearer "12 hours under target")
![Tock_Circles_J](https://user-images.githubusercontent.com/52677065/76127725-6aed6300-5fd0-11ea-9da5-ee74345ff31a.png)

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
